name: Deploy to GDSC DJU Shared Live Channel

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - "packages/gdsc-dju-shared/**"
jobs:
  Deploy_Live_channel:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/gdsc-dju-shared
    environment:
      name: GDSC DJU Shared Production
      url: https://gdsc-dju-shared.web.app
    steps:
      - uses: actions/checkout@v2
      - name: install package
        run: yarn install
      - name: install sitemap package
        run: yarn add babel-cli babel-preset-es2015 babel-preset-react babel-register
        working-directory: ${{ env.working-directory }}
      - name: Project Build
        run: yarn build
        working-directory: ${{ env.working-directory }}
      - name: Generate sitemap
        run: node sitemap-builder.js
        working-directory: ${{ env.working-directory }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: run_firebase_deploy
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDSC_DJU_SHARED }}'
          channelId: live
          projectId: gdsc-dju-shared
          entryPoint: './packages/gdsc-dju-shared'
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_SHARED_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_SHARED_WEBHOOK_TOKEN }}
          color: "#4285f4"
          args: |
            gdsc-dju-shared has been deployed to Live channel
            `Contributor` ${{github.actor}}
            `Event Status` ${{github.event_name}}
            `URL` https://gdsc-dju-shared.web.app
            `Build Time` ${{steps.run_firebase_deploy.outputs.expire_time}}
