name: Deploy to GDSC DJU Web Preview Channel

on:
  push:
    paths:
      - "packages/gdsc-dju-web/**"
      - ".github/workflows/gdsc-dju-Web-deploy-preview.yml"
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
      - develop
    paths:
      - "packages/gdsc-dju-web/**"
jobs:
  Deploy_preview_channel:
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/gdsc-dju-web
    environment:
      name: GDSC DJU Web Preview
      url: ${{ steps.run_firebase_preview.outputs.details_url }}
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: tsc && yarn build
        working-directory: ${{ env.working-directory }}
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        working-directory: ${{ env.working-directory }}
      - name: Setting .env
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_DATABASE_URL=${{ secrets.VITE_FIREBASE_DATABASE_URL }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_FIREBASE_APPID=${{ secrets.VITE_FIREBASE_APPID }}" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> .env
          cat .env
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: run_firebase_preview
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDSC_DJU }}'
          projectId: gdsc-dju
          expires: 3d
          channelId: ' ${{ steps.slug.outputs.sha8 }}-${{ github.event.pull_request.head.ref }} '
          entryPoint: './packages/gdsc-dju-web'
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_SHARED_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_SHARED_WEBHOOK_TOKEN }}
          color: "#4285f4"
          args: |
            gdsc-dju-Web has been deployed to Preview channel
            `Contributor`: ${{github.actor}}
            `Event Status` ${{github.event_name}}
            `URL` <${{steps.run_firebase_preview.outputs.details_url}}>
            `Build Time` ${{steps.run_firebase_preview.outputs.expire_time}}
      
