name: Deploy to GDSC DJU DESIGN Live Channel

on:
  push:
    paths:
      - "packages/gdsc-dju-design/**"
      - ".github/workflows/gdsc-dju-design-deploy-preview.yml"
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
      - develop
    paths:
      - "packages/gdsc-dju-design/**"
      - ".github/workflows/gdsc-dju-design-deploy-preview.yml"
jobs:
  Deploy_Live_channel:
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/gdsc-dju-design
    environment:
      name: GDSC DJU Design Preview
      url: ${{ steps.run_firebase_preview.outputs.details_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Setting .env
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_DATABASE_URL=${{ secrets.VITE_FIREBASE_DATABASE_URL }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_FIREBASE_APPID=${{ secrets.VITE_FIREBASE_APPID }}" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> .env
          cat .env
        working-directory: ${{ env.working-directory }}
      - name: install package
        run: yarn install
      - name: build-storybook
        run: yarn build-storybook
        working-directory: ${{ env.working-directory }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: run_firebase_preview
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDSC_DJU }}'
          projectId: gdsc-dju
          target: gdsc-dju-design
          expires: 3d
          channelId: ' ${{ steps.slug.outputs.sha8 }}-${{ github.event.pull_request.head.ref }} '
          entryPoint: './packages/gdsc-dju-design'
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_DESIGN_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_DESIGN_WEBHOOK_TOKEN }}
          color: "#4285f4"
          args: |
            gdsc-dju-design has been deployed to Live channel
            `Contributor` ${{github.actor}}
            `Event Status` ${{github.event_name}}
            `URL` https://design.gdsc-dju.com
            `Build Time` ${{steps.run_firebase_deploy.outputs.expire_time}}
