name: Deploy to GDSC DJU Shared Preview Channel

on:
  push:
    paths:
      - "packages/gdsc-dju-shared/*"
      - ".github/workflows/gdsc-dju-shared-deploy-preview.yml"
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
      - develop
    paths:
      - "packages/gdsc-dju-shared/*"
jobs:
  Deploy_preview_channel:
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/gdsc-dju-shared
    environment:
      name: GDSC DJU Shared Preview
      url: ${{ steps.run_firebase_preview.outputs.details_url }}
    steps:
      - uses: actions/checkout@v2
      - name: install package
        run: yarn install
      - name: Project Build
        run: yarn build
        working-directory: ${{ env.working-directory }}
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        working-directory: ${{ env.working-directory }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: run_firebase_preview
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDSC_DJU_SHARED }}'
          projectId: gdsc-dju-shared
          channelId: ' ${{ steps.slug.outputs.sha8 }}-${{ github.event.pull_request.head.ref }} '
          entryPoint: './packages/gdsc-dju-shared'
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_SHARED_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_SHARED_WEBHOOK_TOKEN }}
          color: "#4285f4"
          args: |
            gdsc-dju-shared has been deployed to Preview channel
            `Contributor`: ${{github.actor}}
            `Event Status` ${{github.event_name}}
            `URL` <${{steps.run_firebase_preview.outputs.details_url}}>
            `Build Time` ${{steps.run_firebase_preview.outputs.expire_time}}
